server:
  port: 8080

spring:
  application:
    name: loopin-application
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 310MB
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}  # 환경 변수 사용 권장
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2  # AWS 서울 리전
      s3:
        bucket: loopin-bucket-v1 # S3 버킷명
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [ openid, profile, email ]
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ""
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: [ account_email ]
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: [ email ]
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jackson:
    serialization:
      write-dates-as-timestamps: false

custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
  accessToken:
    expiration: 30m    # 30분
  refreshToken:
    expiration: 30d   # 30일

frontend:
  redirect:
    local: http://local.loopin.co.kr/login
    dev: https://develop.loopin.co.kr/login
    prod: https://loopin.co.kr/login

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    groups-order: DESC
    operations-sorter: method
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

security:
  auth:
    dummy-password: "{noop}social-user"  # 실제 인증에 쓰이지 않지만, 빈값 방지용

app:
  oauth:
    ticket-ttl-minutes: 10
