name: CICD - DockerHub Build & Push

on:
  push:
    branches: [ main ]

jobs:
  cd:
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
      MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
      NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
      NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
      MAIL_APP_PASSWORD: ${{ secrets.MAIL_APP_PASSWORD }}
      GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
      OAUTH_STATE_SECRET: ${{secrets.OAUTH_STATE_SECRET}}
      GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
      FIREBASE_ADMIN_SDK_B64: ${{secrets.FIREBASE_ADMIN_SDK_B64}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy docker-compose.prod.yml & deploy.sh to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml,deploy.sh"
          target: "~/deploy/"

      - name: SSH 접속 및 배포
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, JWT_SECRET_KEY, POSTGRES_HOST, POSTGRES_USERNAME, POSTGRES_PASSWORD, MONGODB_USERNAME, MONGODB_PASSWORD, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, KAKAO_CLIENT_ID, NAVER_CLIENT_ID, NAVER_CLIENT_SECRET, MAIL_APP_PASSWORD, GPT_API_KEY, OAUTH_STATE_SECRET, GEMINI_API_KEY, FIREBASE_ADMIN_SDK_B64
          script: |
            set -e  # 오류 발생 시 즉시 중단
            cd ~/deploy
            chmod +x deploy.sh
            umask 077
            printf '%s' "$FIREBASE_ADMIN_SDK_B64" \
              | tr -d '\r\n' \
              | base64 --decode --ignore-garbage \
              > firebase-adminsdk.json
            ./deploy.sh
            echo "Cleaning up old Docker images..."
            docker rmi -f $(docker images junhui9789/loopin-app -q) || true
            docker image prune -f || true
